### ISSUE TITLE
Add Possibility to customize AppendMenuProvider

### ISSUE THREAD

**Issue by AmiciD** [bpmn-io/bpmn-js-create-append-anything#29]
### Is your feature request related to a problem? Please describe.

I have an implementation of bpmn-js version 11.1.0 with all compatible plugins for that version.

Upgrading to the new version, I found that the appendMenuProvider to modify the entries of the appendMenu is no longer exported and modifiable in this package.

### Describe the solution you'd like

I would prefer an approach similar to the old one, where I could import the provider and modify its behavior.

### Describe alternatives you've considered

A working workaround I found is this:
``` javascript
import { CreateAppendAnythingModule } from "bpmn-js-create-append-anything";

const AppendMenuProvider = CreateAppendAnythingModule.__depends__[0].appendMenuProvider[1];
```

Unfortunately, I haven't found anything regarding this new implementation of the appendMenuProvider; I just need to modify and filter the menu entries.

**Comment by nikku** [comment]
Thanks for opening this issue. At this stage it is not easily possible to access the `appendMenuProvider` by sub-classing. 

The general way to subclass is not to "modify providers" through sub-classing, but to provide your own customizing `AppendMenuProvider`:

```javascript

const LOW_PRIORITY = 500;

function MyAppendMenuModifyingProvider(popupMenu, eventBus) {
  
  // register provider
  popupMenu.registerProvider('bpmn-append', this, LOW_PRIORITY);
  
  // own provider method returns middleware
  // (element) => (existingEntires) => newEntries
  
  this.getPopupMenuEntries = function(element) {
    
    return (existingEntries) => {
      // modify <existingEntries> as you wish, add, remove some
      
      return existingEntries;
    };
  };
}
```

Would this work for your case?

**Comment by nikku** [comment]
@AmiciD I'd be interested if https://github.com/bpmn-io/bpmn-js-create-append-anything/issues/29#issuecomment-2058293091 worked for you? I assume so and will close this issue as _won't fix_.

**Comment by AmiciD** [comment]
@nikku unfortunately i had  no time to look for a custom implementation like the one suggested, i will try and give a feedback here asap

**Comment by tony2y** [comment]
Do you have any specific examples?，[https://github.com/bpmn-io/bpmn-js-create-append-anything/issues/29#issuecomment-2058293091](#29)I'm not quite sure what needs to be done @nikku

**Comment by tony2y** [comment]
> 感谢您提出这个问题。目前，`appendMenuProvider`通过子类化来访问还不太容易。
> 
> 子类化的一般方法不是通过子类化来“修改提供程序”，而是提供您自己的定制`AppendMenuProvider`：
> 
> ```js
> const LOW_PRIORITY = 500;
> 
> function MyAppendMenuModifyingProvider(popupMenu, eventBus) {
>   
>   // register provider
>   popupMenu.registerProvider('bpmn-append', this, LOW_PRIORITY);
>   
>   // own provider method returns middleware
>   // (element) => (existingEntires) => newEntries
>   
>   this.getPopupMenuEntries = function(element) {
>     
>     return (existingEntries) => {
>       // modify <existingEntries> as you wish, add, remove some
>       
>       return existingEntries;
>     };
>   };
> }
> ```
> 
> 这对你的情况有用吗？
Do you have any specific examples? I'm not quite sure what needs to be done @nikku

**Comment by tony2y** [comment]
I want to extend a ServiceTask (type=email). After clicking, the default businessObject will have type=email. How can I implement it? @nikku

**Comment by barmac** [comment]
For the usage questions, please use the forum: https://forum.bpmn.io/
