### ISSUE TITLE
ContextPad#getPad is deprecated and will be removed in future library versions

### ISSUE THREAD

**Issue by ruanzy** [bpmn-io/bpmn-js-create-append-anything#34]
Error: ContextPad#getPad is deprecated and will be removed in future library versions

 diagram-js  version updater

<img width="698" alt="1719651677061_B976675D-84EF-4960-85FA-746AD26778CD" src="https://github.com/bpmn-io/bpmn-js-create-append-anything/assets/7534072/004abce5-e078-4aed-a43c-22e631e128c5">

**Comment by nikku** [comment]
We'll look into the issue. Our tools shall be compatible, and future proof.

**Comment by BSekula** [comment]
Is there any update on this issue?

**Comment by barmac** [comment]
We are not actively working on this right now, but will be happy to review a contribution.
